### ISSUE TITLE
Project produces many warnings

### ISSUE THREAD

**Issue by aaronfranke** [tanjunior/godot-openworld-archero#1]
When I run this project, there are many warnings. Consider fixing them. 

![Untitled](https://user-images.githubusercontent.com/1646875/76911595-8df8fc00-6887-11ea-942b-1a3ce16736d5.png)

Also, consider making your code conform to the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html).

**Comment by tanjunior** [comment]
warning is not game breaking.

pushed a new commit
made a few warning not show as it is annoying you
improved closest enemy target system which also eliminated the error in your screenshot
added FSM, navmesh AI and healthbar
